//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZORTRANS
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Soferi
    {
        public string Categorie_Permis { get; set; }
        public int ID_SOFER_MASINA { get; set; }
        public int ID_ANGAJAT { get; set; }
        public Nullable<int> ID_DISPECER { get; set; }
    
        public virtual Angajati Angajati { get; set; }
        public virtual Masini Masini { get; set; }
    }
}
