//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZORTRANS
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Locatii
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Locatii()
        {
            this.Persoane_Fizice = new ObservableCollection<Persoane_Fizice>();
            this.Persoane_Juridice = new ObservableCollection<Persoane_Juridice>();
            this.Transporturis = new ObservableCollection<Transporturi>();
        }
    
        public int ID_LOCATIE { get; set; }
        public string Oras { get; set; }
        public string Strada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Persoane_Fizice> Persoane_Fizice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Persoane_Juridice> Persoane_Juridice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Transporturi> Transporturis { get; set; }
    }
}
