//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZORTRANS
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Masini
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Masini()
        {
            this.Soferis = new ObservableCollection<Soferi>();
        }
    
        public string Marca { get; set; }
        public string Model { get; set; }
        public string Tip { get; set; }
        public int ID_MASINA { get; set; }
        public string Numar_Inmatriculare { get; set; }
        public int ID_TRANSPORT { get; set; }
    
        public virtual Transporturi Transporturi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Soferi> Soferis { get; set; }
    }
}
