//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZORTRANS
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Transporturi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporturi()
        {
            this.Masinis = new ObservableCollection<Masini>();
        }
    
        public int ID_TRANSPORT { get; set; }
        public string Adresa_Plecare { get; set; }
        public string Adresa_Destinatie { get; set; }
        public int Distanta_km_ { get; set; }
        public string Marfa { get; set; }
        public double Greutate_Marfa_t_ { get; set; }
        public double Pret_km { get; set; }
        public System.DateTime Data { get; set; }
        public int ID_LOCATIE { get; set; }
    
        public virtual Locatii Locatii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Masini> Masinis { get; set; }
    }
}
